let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
strip.showColor(neopixel.colors(NeoPixelColors.Red))
strip.show()
basic.pause(1000)
strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Violet))
strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Orange))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Purple))
strip.show()
basic.forever(function () {
    strip.setPixelColor(randint(0, 3), neopixel.rgb(randint(0, 225), randint(0, 255), randint(0, 255)))
    strip.rotate(1)
    strip.show()
    basic.pause(100)
})
